
package market;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CategoryFr1 extends javax.swing.JFrame {

    public CategoryFr1() {
        initComponents();
    }
String url,uname,pwd;
Connection con;
Statement st;
ResultSet rs;
PreparedStatement pr;
public void SelectSeller(){
    try{
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/market","suba","232266");
      String  qry=("Select * from categorytb;");
      pr=con.prepareStatement(qry);
       rs=  pr.executeQuery(qry);
       DefaultTableModel dtb=(DefaultTableModel)catTb.getModel();
    while(rs.next()){
        dtb.addRow(new String[] {rs.getString(1),rs.getString(2),rs.getString(3)});
    }
    }
    catch(Exception ex){
        System.out.println(ex);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panels3 = new market.panels();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        catName = new javax.swing.JTextField();
        catId = new javax.swing.JTextField();
        catDesc = new javax.swing.JTextField();
        editbtn1 = new market.Btns();
        deletebtn1 = new market.Btns();
        clrbtn1 = new market.Btns();
        addbtn = new market.Btns();
        jScrollPane1 = new javax.swing.JScrollPane();
        catTb = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panels3.setColor1("#FFAFBD");
        panels3.setColor2("#FFD194");
        panels3.setSide(1500);

        jLabel6.setBackground(new java.awt.Color(153, 204, 255));
        jLabel6.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MANAGE CATEGORIES.....");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CategoryId :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Name :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Description  :");

        catName.setBackground(new java.awt.Color(204, 204, 204));
        catName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        catId.setBackground(new java.awt.Color(204, 204, 204));
        catId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        catDesc.setBackground(new java.awt.Color(204, 204, 204));
        catDesc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        editbtn1.setForeground(new java.awt.Color(255, 255, 255));
        editbtn1.setColor("#65C7F7");
        editbtn1.setColor2("#0052D4");
        editbtn1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        editbtn1.setLabel("EDIT");
        editbtn1.setRadius(50);
        editbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbtn1MouseClicked(evt);
            }
        });

        deletebtn1.setForeground(new java.awt.Color(255, 255, 255));
        deletebtn1.setColor("#65C7F7");
        deletebtn1.setColor2("#0052D4");
        deletebtn1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        deletebtn1.setLabel("DELETE");
        deletebtn1.setRadius(50);
        deletebtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebtn1MouseClicked(evt);
            }
        });

        clrbtn1.setForeground(new java.awt.Color(255, 255, 255));
        clrbtn1.setColor("#65C7F7");
        clrbtn1.setColor2("#0052D4");
        clrbtn1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        clrbtn1.setLabel("CLEAR");
        clrbtn1.setRadius(50);
        clrbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clrbtn1MouseClicked(evt);
            }
        });
        clrbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrbtn1ActionPerformed(evt);
            }
        });

        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("ADD");
        addbtn.setColor("#65C7F7");
        addbtn.setColor2("#0052D4");
        addbtn.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        addbtn.setRadius(50);
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
        });

        catTb.setBackground(new java.awt.Color(230, 252, 255));
        catTb.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        catTb.setForeground(new java.awt.Color(153, 0, 153));
        catTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "DESCRIPTION"
            }
        ));
        catTb.setGridColor(new java.awt.Color(204, 204, 255));
        catTb.setIntercellSpacing(new java.awt.Dimension(0, 0));
        catTb.setRowHeight(30);
        catTb.setSelectionBackground(new java.awt.Color(255, 153, 255));
        catTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catTbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(catTb);

        jLabel10.setBackground(new java.awt.Color(153, 204, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PRODUCTS");
        jLabel10.setToolTipText("");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELLER");
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(153, 204, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("LOGOUT");
        jLabel11.setToolTipText("");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panels3Layout = new javax.swing.GroupLayout(panels3);
        panels3.setLayout(panels3Layout);
        panels3Layout.setHorizontalGroup(
            panels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panels3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panels3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(panels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panels3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(catDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(panels3Layout.createSequentialGroup()
                        .addGroup(panels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panels3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(185, 185, 185)
                                .addComponent(catId, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(259, 259, 259)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panels3Layout.createSequentialGroup()
                                .addGap(453, 453, 453)
                                .addComponent(jLabel6)))
                        .addContainerGap(86, Short.MAX_VALUE))))
            .addGroup(panels3Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(editbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(clrbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(deletebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panels3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        panels3Layout.setVerticalGroup(
            panels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panels3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(panels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(panels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clrbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deletebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panels3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panels3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1347, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panels3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panels3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clrbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrbtn1MouseClicked
    catId.setText("");
    catName.setText("");
    catDesc.setText("");
    catId.setFocusable(true);
    }//GEN-LAST:event_clrbtn1MouseClicked

    private void clrbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clrbtn1ActionPerformed

    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked
       if(catId.getText().isEmpty()||catName.getText().isEmpty()||catDesc.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Missing Information");   
      }
      else{
      try{
        Class.forName("com.mysql.cj.jdbc.Driver");
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/market","suba","232266");
      String qry;
      qry=("Insert Into categorytb values(?,?,?);");
      pr=con.prepareStatement(qry);
      pr.setInt(1, Integer.valueOf(catId.getText()));
      pr.setString(2,catName.getText());
      pr.setString(3, catDesc.getText());
      int row=pr.executeUpdate();
      JOptionPane.showMessageDialog(this, "Category Successfully Added");
      con.close();
      SelectSeller();
      }catch(Exception ex){
        System.out.println(ex);
    }
    }                                   
    
    }//GEN-LAST:event_addbtnMouseClicked

    private void catTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catTbMouseClicked
      DefaultTableModel model=(DefaultTableModel)catTb.getModel();
      int Myindex=catTb.getSelectedRow();
      catId.setText(model.getValueAt(Myindex,0).toString());
      catName.setText(model.getValueAt(Myindex,1).toString());
      catDesc.setText(model.getValueAt(Myindex,2).toString());
    }//GEN-LAST:event_catTbMouseClicked

    private void editbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbtn1MouseClicked
       if(catId.getText().isEmpty()||catName.getText().isEmpty()||catDesc.getText().isEmpty()){
          JOptionPane.showMessageDialog(this, "Missing Information");
        }else{
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/market","suba","232266");
      String CId=catId.getText();
      String  qry="update  categorytb set CatName='"+catName.getText()+"'"+",CatDesc='"+catDesc.getText()+"'"+"where CatId="+catId.getText();
      pr=con.prepareStatement(qry);
      pr.executeUpdate(qry);
      SelectSeller();
        JOptionPane.showMessageDialog(this, "Category Updated");
            }
            catch(Exception ex){
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_editbtn1MouseClicked

    private void deletebtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtn1MouseClicked
       if(catId.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Category To Be Deleted");

        }else{
          try{ 
             Class.forName("com.mysql.cj.jdbc.Driver");
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/market","suba","232266");
      String CId=catId.getText();
      String  qry="delete from categorytb where CatId="+CId;
      pr=con.prepareStatement(qry);
      pr.executeUpdate(qry);
      SelectSeller();
        JOptionPane.showMessageDialog(this, "Category Deleted Successfully");
          } 
        
        catch(Exception ex){
              System.out.println(ex);
          }
    }                        
    }//GEN-LAST:event_deletebtn1MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        new MPFr().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new BillFr().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new LoginFr().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryFr1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryFr1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryFr1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryFr1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryFr1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private market.Btns addbtn;
    private javax.swing.JTextField catDesc;
    private javax.swing.JTextField catId;
    private javax.swing.JTextField catName;
    private javax.swing.JTable catTb;
    private market.Btns clrbtn1;
    private market.Btns deletebtn1;
    private market.Btns editbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private market.panels panels3;
    // End of variables declaration//GEN-END:variables
}
